# Header
menu:
  Home: /
  About: /#about
  Team: /#team
  Blog: http://blog.trackfellas.com
  Sign up: /#signup
  Get in touch: /#contact
  
rss: /atom.xml

# Content
excerpt_link: Read More


# Miscelaneous
favicon: /favicon.png
